//! The offline activation-code format (PLAN §4.10 "licence with trial and
//! expiry · UID machine binding", §12's "recovery procedure tied to the
//! licence", §23 item 4). One crate, shared by two consumers that must
//! never disagree about the byte layout:
//!
//! - `app/src-tauri` (path dependency) — **verifies** codes an operator
//!   pastes in, using the [`VENDOR_PUBLIC_KEY`] baked into the binary. It
//!   never holds a private key and never signs anything.
//! - `tools/licensegen` (path dependency) — the offline, never-shipped tool
//!   Babulens runs by hand to turn a customer's request code into an
//!   activation code. It holds the private key (a local `vendor.key` file,
//!   gitignored, never committed — same rule as `net::tunnel`'s connector
//!   token: a secret that must never reach the repository).
//!
//! **Why asymmetric signing at all**, when `settings::adminAuth` gets away
//! with plain salted SHA-256 ("no new crypto surface")? Different threat
//! model. The admin password hash never leaves one machine's database — an
//! attacker needs that specific machine's specific row before the hash is
//! useful for anything. An activation-code *verifier*, by contrast, ships
//! inside every public download of this app. If it verified with a shared
//! secret, that secret would be sitting in every installer, and anyone
//! could read it out and mint their own "valid" codes — the checker would
//! be checking against itself. Ed25519 signing is the one thing that keeps
//! "verify" (public, ships to everyone) and "issue" (private, stays with
//! Babulens) from being the same operation. This genuinely is a new crypto
//! surface, and it exists because the feature cannot work without one.
//!
//! ## Wire format
//!
//! An **activation code** is `base32(payload ++ signature)`, grouped into
//! 5-character blocks joined by `-` for readability when pasted or read
//! aloud. `payload` is 13 bytes, big-endian:
//!
//! | Bytes | Field | Meaning |
//! |---|---|---|
//! | 0 | `version` | Format version — `1` today. Lets the layout evolve without breaking codes already issued under it. |
//! | 1–8 | `machine_hash` | `u64` — first 8 bytes of `SHA-256(machine UID)`. Binds the code to one PC without embedding the raw UID in something a customer might paste into a support forum. |
//! | 9–10 | `issued_days` | `u16` — days since [`EPOCH`], the day this code was signed. Record-keeping; not itself checked at verify time. |
//! | 11–12 | `expires_days` | `u16` — days since [`EPOCH`] the code stops being valid. `0` is the sentinel for "perpetual — never expires". |
//!
//! `signature` is the 64-byte Ed25519 signature of those 13 payload bytes
//! under the vendor's private key. Total: 77 bytes, ~124 base32 characters,
//! ~25 dashed groups — long enough that pasting (email, or the file-import
//! path task #38 adds) is the expected path, with manual typing as a
//! fallback rather than the primary design target.
//!
//! A **request code** is shorter and unsigned — it carries no authority by
//! itself, so it needs no signature. `base32(version ++ machine_hash)`, 9
//! bytes raw, ~15 base32 characters, ~3 dashed groups: short enough to read
//! over a phone call. The operator generates one from Settings → System
//! (task #38) and sends it to Babulens by whatever channel is convenient;
//! Babulens turns it into an activation code with `tools/licensegen sign`
//! and sends that back the same way. Nothing here ever touches a network —
//! "offline activation" means the whole exchange happens over an
//! out-of-band channel the app is never a party to.
//!
//! ## What this format deliberately cannot do
//!
//! There is no revocation check, because there is nothing to check against
//! offline — a machine with no network path can't ask anyone whether a code
//! is still good. `expires_days` is the only leash: perpetual codes really
//! are perpetual once issued. If online revocation ever matters, it rides
//! the same LAN/tunnel surface `net`/`net::tunnel` already build (PLAN §18),
//! as an *additional* check layered on top of this one, not a replacement
//! for it — offline verification must keep working with no network at all,
//! since that is the entire point of the feature.

use chrono::NaiveDate;
use data_encoding::BASE32_NOPAD_NOCASE;
use ed25519_dalek::{Signature, Signer, SigningKey, Verifier, VerifyingKey};
use thiserror::Error;

/// **Development placeholder.** Generated by one throwaway `licensegen
/// keygen` run while building this format (task #37) — not Babulens' real
/// signing key, which does not exist yet (PLAN §23 item 4, "pricing and
/// licence tiers", is still an open decision this key rotation waits on).
/// Every activation code issued against this placeholder becomes worthless
/// the moment it is replaced, which is the intended behaviour: rotating
/// this constant is how a real key gets adopted before 3.0 actually ships,
/// exactly like the `BLS` logo placeholder in §23 item 1 is one swap away
/// from the real mark. Whoever does that swap must keep the matching
/// `vendor.key` (see `tools/licensegen`) somewhere that is not this
/// repository.
pub const VENDOR_PUBLIC_KEY: [u8; 32] = [
    0xf6, 0x64, 0x10, 0x08, 0xbe, 0x70, 0xf1, 0x59, 0xd6, 0xaf, 0x40, 0xfe, 0x4c, 0xc3, 0x57, 0x3d,
    0x77, 0xc6, 0xac, 0x82, 0x73, 0xfc, 0xe2, 0x05, 0xb7, 0x6c, 0x8a, 0x9f, 0x2f, 0xd0, 0x01, 0x6e,
];

/// Format version this crate reads and writes. Bump alongside a deliberate
/// layout change, never silently.
pub const FORMAT_VERSION: u8 = 1;

const PAYLOAD_LEN: usize = 13;
const SIGNATURE_LEN: usize = 64;

#[derive(Debug, Error)]
pub enum LicenseFormatError {
    #[error("that code isn't in the right shape — check for a missing character")]
    Malformed,
    #[error("unrecognised code format (version {0}) — this build only understands version {FORMAT_VERSION}")]
    UnsupportedVersion(u8),
    #[error("that code's signature doesn't check out — it may be mistyped, or not a genuine BabuScales code")]
    BadSignature,
    #[error("internal: {0}")]
    Internal(&'static str),
}

/// Everything an activation code, once verified, says about the licence it
/// grants. Carries no opinion on *whether* it's currently valid for this
/// machine or this moment — that comparison is the caller's job (it needs
/// "now" and "this machine's hash", neither of which belongs in a format
/// crate that has no clock and no OS access).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LicensePayload {
    pub machine_hash: u64,
    pub issued_on: NaiveDate,
    /// `None` — perpetual, the `expires_days == 0` sentinel decoded.
    pub expires_on: Option<NaiveDate>,
}

/// Day zero for the compact `u16` day-counts above. Chosen close to this
/// project's own start rather than the Unix epoch purely so a decoded
/// `issued_days` value is small and recognisable while debugging; it has
/// no other significance and issuing codes right up to `EPOCH + 65535`
/// days (the y2205 problem, roughly) is not a concern anyone alive today
/// needs to plan around.
fn epoch() -> Result<NaiveDate, LicenseFormatError> {
    NaiveDate::from_ymd_opt(2026, 1, 1).ok_or(LicenseFormatError::Internal("bad epoch constant"))
}

fn date_to_days(date: NaiveDate) -> Result<u16, LicenseFormatError> {
    let delta = date.signed_duration_since(epoch()?).num_days();
    u16::try_from(delta).map_err(|_| LicenseFormatError::Internal("date out of encodable range"))
}

fn days_to_date(days: u16) -> Result<NaiveDate, LicenseFormatError> {
    epoch()?
        .checked_add_days(chrono::Days::new(u64::from(days)))
        .ok_or(LicenseFormatError::Internal("date overflow"))
}

fn format_code(raw: &[u8]) -> String {
    let flat = BASE32_NOPAD_NOCASE.encode(raw);
    flat.as_bytes()
        .chunks(5)
        .map(|chunk| std::str::from_utf8(chunk).unwrap_or_default())
        .collect::<Vec<_>>()
        .join("-")
}

fn parse_code(code: &str) -> Result<Vec<u8>, LicenseFormatError> {
    let cleaned: String = code
        .chars()
        .filter(|c| !c.is_whitespace() && *c != '-')
        .collect();
    BASE32_NOPAD_NOCASE
        .decode(cleaned.as_bytes())
        .map_err(|_| LicenseFormatError::Malformed)
}

/// Builds the ~15-character request code an operator reads out or pastes
/// to Babulens — see the module doc's "What this format deliberately
/// cannot do" for why it carries no signature.
pub fn encode_request_code(machine_hash: u64) -> String {
    let mut raw = Vec::with_capacity(9);
    raw.push(FORMAT_VERSION);
    raw.extend_from_slice(&machine_hash.to_be_bytes());
    format_code(&raw)
}

/// The inverse of [`encode_request_code`] — `tools/licensegen sign` reads
/// a customer's request code back into the machine hash it should issue
/// against.
pub fn decode_request_code(code: &str) -> Result<u64, LicenseFormatError> {
    let raw = parse_code(code)?;
    if raw.len() != 9 {
        return Err(LicenseFormatError::Malformed);
    }
    if raw[0] != FORMAT_VERSION {
        return Err(LicenseFormatError::UnsupportedVersion(raw[0]));
    }
    let bytes: [u8; 8] = raw[1..9]
        .try_into()
        .map_err(|_| LicenseFormatError::Internal("machine hash slice wrong length"))?;
    Ok(u64::from_be_bytes(bytes))
}

/// `tools/licensegen sign` only — builds and signs a fresh activation code.
/// Never called from the app (which has no private key to call it with).
pub fn sign_activation_code(
    signing_key: &SigningKey,
    machine_hash: u64,
    issued_on: NaiveDate,
    expires_on: Option<NaiveDate>,
) -> Result<String, LicenseFormatError> {
    let mut payload = Vec::with_capacity(PAYLOAD_LEN);
    payload.push(FORMAT_VERSION);
    payload.extend_from_slice(&machine_hash.to_be_bytes());
    payload.extend_from_slice(&date_to_days(issued_on)?.to_be_bytes());
    let expires_days = match expires_on {
        Some(date) => date_to_days(date)?,
        None => 0,
    };
    payload.extend_from_slice(&expires_days.to_be_bytes());

    let signature = signing_key.sign(&payload);
    let mut raw = payload;
    raw.extend_from_slice(&signature.to_bytes());
    Ok(format_code(&raw))
}

/// The app's one entry point: decode, check the signature against
/// [`VENDOR_PUBLIC_KEY`], and hand back what the code says — or a reason
/// it can't be trusted. Does **not** check the machine hash or the expiry
/// against "now"; the caller (which alone knows both) does that, so this
/// function stays a pure "is this bit pattern genuinely Babulens-signed"
/// check with nothing else mixed in.
pub fn verify_activation_code(code: &str) -> Result<LicensePayload, LicenseFormatError> {
    let raw = parse_code(code)?;
    if raw.len() != PAYLOAD_LEN + SIGNATURE_LEN {
        return Err(LicenseFormatError::Malformed);
    }
    let (payload_bytes, signature_bytes) = raw.split_at(PAYLOAD_LEN);

    if payload_bytes[0] != FORMAT_VERSION {
        return Err(LicenseFormatError::UnsupportedVersion(payload_bytes[0]));
    }

    let verifying_key = VerifyingKey::from_bytes(&VENDOR_PUBLIC_KEY)
        .map_err(|_| LicenseFormatError::Internal("embedded public key is malformed"))?;
    let sig_array: [u8; SIGNATURE_LEN] = signature_bytes
        .try_into()
        .map_err(|_| LicenseFormatError::Internal("signature slice wrong length"))?;
    let signature = Signature::from_bytes(&sig_array);
    verifying_key
        .verify(payload_bytes, &signature)
        .map_err(|_| LicenseFormatError::BadSignature)?;

    let machine_hash = u64::from_be_bytes(
        payload_bytes[1..9]
            .try_into()
            .map_err(|_| LicenseFormatError::Internal("machine hash slice wrong length"))?,
    );
    let issued_days = u16::from_be_bytes([payload_bytes[9], payload_bytes[10]]);
    let expires_days = u16::from_be_bytes([payload_bytes[11], payload_bytes[12]]);

    Ok(LicensePayload {
        machine_hash,
        issued_on: days_to_date(issued_days)?,
        expires_on: if expires_days == 0 {
            None
        } else {
            Some(days_to_date(expires_days)?)
        },
    })
}
